apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-workshop-build
  description: Build artifacts and scripts for the Backstage workshop
  annotations:
    github.com/project-slug: POps-Rox/backstage-workshop-build
    backstage.io/techdocs-ref: dir:.
  tags:
    - backstage
    - platform-ops
  links:
    - url: https://github.com/POps-Rox/backstage-workshop-build
      title: GitHub Repository
      icon: github
spec:
  type: service
  owner: platform-ops-team
  lifecycle: production
  system: pops-rox-platform
